env:
  global:
    - CC_TEST_REPORTER_ID=REPORTER
language: node_js

cache:
  directories:
    - node_modules
    - client/node_modules
    - packages/react-scripts/node_modules
  
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run coverage