export const TEST_DISPATCH = 'TEST_DISPATCH'
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const USER_LOADING = 'USER_LOADING'

export const GET_FAMILY = 'GET_FAMILY'
export const GET_FAMILIES = 'GET_FAMILIES'
export const FAMILY_LOADING = 'FAMILY_LOADING'
export const CLEAR_CURRENT_FAMILY = 'CLEAR_CURRENT_FAMILY'

export const GET_CURRENT_FAMILY = 'GET_CURRENT_FAMILY'
export const ADD_FAMILY_TO_WAITLIST = 'ADD_FAMILY_TO_WAITLIST'
